package net.nueca.imonggosdk.enums;

/**
 * Created by rhymart on 8/22/15.
 * imonggosdk2 (c)2015
 */
public enum ConcessioModule {
    STOCK_REQUEST, // ORders
    PURCHASE_ORDERS,
    PHYSICAL_COUNT,
    INVOICE, // SALES, // BOOKING
    RECEIVE_BRANCH, // RECEIVE
    RECEIVE_BRANCH_PULLOUT, // PULLOUT CONFIRMATION
    RELEASE_BRANCH, // PULLOUT_REQUEST || Pullout Document
    RECEIVE_ADJUSTMENT, //ADJUSTMENT_OUT, // MSO
    RELEASE_ADJUSTMENT, //ADJUSTMENT_IN,
    RECEIVE_SUPPLIER, // RECEIVE(REBISCO)
    RELEASE_SUPPLIER, // PULLOUT(REBISCO)

    CUSTOMERS,
    RELEASE_CUSTOMER,
    CUSTOMER_DETAILS,

    APP,

    HISTORY,
    LAYAWAY,
    ROUTE_PLAN
}
