package net.nueca.imonggosdk.enums;

/**
 * Created by rhymart on 5/13/15.
 * imonggosdk (c)2015
 */
public enum Table {
    BRANCHES,
    BRANCH_PRICES,
    BRANCH_TAGS,
    CUSTOMERS,
    INVENTORIES,
    PRODUCTS,
    PRODUCT_TAGS,
    PRODUCT_EXTRAS,
    SESSIONS,
    TAX_RATES,
    TAX_SETTINGS,
    UNITS,
    USERS,

    BRANCH_USERS,
    PRODUCT_TAX_RATES,
    CUSTOMER_CUSTOMER_GROUP,
    PRODUCT_SALES_PROMOTION,

    DOCUMENTS,
    DOCUMENT_TYPES,
    DOCUMENT_PURPOSES,
    DOCUMENT_LINES,
    EXTENDED_ATTRIBUTES,
    DOCUMENT_LINE_EXTRAS,

    INVOICES,
    INVOICE_LINES,
    INVOICE_TAX_RATES,
    PAYMENTS,

    SALES_PROMOTIONS,

    SETTINGS,
    TOKENS,
    APPLICATION_SETTINGS,
    LAST_UPDATED_AT,
    POS_DEVICES,

    OFFLINEDATA,

    ORDERS,
    ORDER_LINES,
    DAILY_SALES,

    // ----- FOR REBISCO
    CUSTOMER_GROUPS,
    CUSTOMER_CATEGORIES,
    PRICES,
    PRICE_LISTS,
    ROUTE_PLANS,
    INVOICE_PURPOSES,
    PAYMENT_TERMS,
    PAYMENT_TYPES,
    EXTRAS
}
